
services:
  nginx:
    container_name: cv-nginx
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    extra_hosts:
      - "local.regal-wings:host-gateway"

  php:
    image: cv-php
    build:
      context: php/
      args:
        WORKDIR: /var/www
    container_name: cv-php
    restart: unless-stopped
    volumes:
      - ../:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/php-fpm.ini
    networks:
      - laravel
    extra_hosts:
      - "local.regal-wings:host-gateway"
    user: '1000'

  mysql:
    container_name: cv-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cv
      MYSQL_ROOT_PASSWORD: cv_pw
      MYSQL_PASSWORD: cv_pw
      MYSQL_USER: cv_user
    ports:
      - "3306:3306"
    volumes:
      - ../.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - laravel

  mysql_test:
    container_name: cv-mysql-test
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cv_test
      MYSQL_ROOT_PASSWORD: cv_pw
      MYSQL_PASSWORD: cv_pw
      MYSQL_USER: cv_user
    ports:
      - "3307:3306"
    volumes:
      - ../.docker/mysql/dbdata_test:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    container_name: cv-pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8888:80"
    environment:
      PMA_HOST: cv-mysql
      PMA_PORT: 3306
      PMA_USER: cv_user
      PMA_PASSWORD: cv_pw
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: cv-redis
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
